# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SSW 858
email: whopper@smith.edu
author: "Herp"
description: >- # this means to ignore newlines until "baseurl:"
  Slides, problem sets, and miscellaneous materials for Smith SSW 858 and 859 taught by Will Hopper.
baseurl: "/SSW-858" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  wjhopper
repository: wjhopper/SSW-858

# Build settings
markdown: kramdown
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
highlighter: rouge
permalink: none

# jekyll-paginate configuration
paginate: 15

sass:
  sass_dir: assets/css
  style: :nested

defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: /posts/:title

collections:
   lectures:
      order:
         - "Intro to R and RStudio"
         - "Data Visualization with ggplot"
         - "Data Types and Manipulation"
         - "Data Manipulation with dplyr"
   problem_sets:
      order:
         - "Intro to R and RStudio"
         - "Data Visualization with ggplot"
         - "Data Wrangling"
         - "Bivariate Regression"
         - "Multiple Regression"
         - "Sampling Distributions"
         - "Confidence Intervals"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - LICENCSE.md
   - renv/
   - renv.lock
   - SSW-858.Rproj
   - R/
