
---
title: 'Problem Set: Confidence Intervals'
author: "Will Hopper"
output:
  html_document:
    css: "https://wjhopper.github.io/SSW-858/assets/css/lab.css"
    theme: lumen
    toc: yes
    toc_float:
      collapsed: false
    toc_depth: 2
    df_print: paged
    self_contained: true
editor_options: 
  chunk_output_type: console
---

In this problem set, we'll practice constructing and interpreting confidence intervals using data on textbook prices. These data were collected during the Fall 2018 semester at UCLA, to compare prices at the campus bookstore to prices on Amazon.com

Importantly, these data represent a *sample* of textbook prices for courses at UCLA, because not all courses from the Fall 2018 are included in the data set. Thus, all of our statistics will be sample statistics that *estimate* true population parameters. 

As always, begin by loading the necessary packages, and the data. Don't forget to explore the data using `glimpse`, `skim`, or just in the R Studio data viewer.

```{r, message=FALSE}
library(skimr)
library(ggplot2)
library(moderndive)
library(infer)
library(dplyr)

textbooks <- read.csv("https://wjhopper.github.io/SSW-858/data/ucla_textbooks_f18.csv")
```

# Data Exploration

## Exercise
Report the sample mean and sample variance of new textbook prices at the campus bookstore and new textbook prices on Amazon.com. Compare the statistics you find for the campus bookstore to those on Amazon.com.

### Solution


# Bootstrap Confidence Intervals

For exercises in this section, feel free use either the `infer` package workflow described in [ModernDive Chapter 8.4](https://moderndive.com/8-confidence-intervals.html#infer-workflow), or do things the "old fashioned" way (e.g., using `dplyr`, `ggplot` and `rep_sample_n` directly). Just be sure not to "mix and match" i.e., don't start off using `rep_sample_n` directly, and switch to using `infer` package functions halfway through (because they won't work correctly!).

**Note:** Just like last week's problem set, don't forget to seed your computer's Random Number Generator using the `set.seed()` function before doing any computations that require random sampling! That way, you'll get the same sample every time you run that code chunk or knit your document. To help remind you, I'll include a "suggested seed" for every exercise where random sampling is necessary.


## Exercise
Construct a bootstrap sampling distribution of the average price for new textbooks at the campus bookstore using 1,000 bootstrap replicates. Visualize the bootstrap distribution using a histogram, and describe the distribution you see.

**Suggested Seed: `set.seed(54321)`**

### Solution


## Exercise
Find the 95% confidence interval of the bootstrap distribution. What does this interval tell you? Be as precise as possible in your answer.

### Solution


# Single-sample Confidence Intervals

## Exercise
Estimate the **90%** confidence interval for new textbook prices at the campus bookstore data based on just the original sample (i.e., using the `textbooks` data frame without bootstrapping).

**Hints** The central limit theorem will be useful, as will the quantile conversion formula from [ModernDive 8.3.2](https://moderndive.com/8-confidence-intervals.html#se-method).

### Solution


## Exercise
Why is the interval created in Exercise 4 narrower than the one created in Exercise 3?

### Solution


# Interpreting Confidence Intervals 

## Exercise
Inspired by your analyses, your friend Francesca decides to sample 100 new textbook prices at their college's bookstore, and construct an 85% confidence interval around the mean new textbook price. What is the probability that their confidence interval contains the true population mean of new textbook prices? Briefly explain how you reached this answer.

### Solution


## Exercise
Francesca 85% confidence interval ranges from \$68 (lower boundary) to \$87 (upper boundary). Does their confidence interval contain the true population mean? If so, how can you tell? If not, can you report the probability that the true population mean of new textbook prices lies between \$68 and \$87? Be sure to exaplin your answers.

### Solution

## Exercise
Explain to Francesca has been learned by finding that the 85% Confidence Interval ranges from \$68 to \$87?

### Solution


